version: '3'
services:
  envoy:
    command:
      - --log-level debug
      - --config-path /etc/envoy/envoy.yaml
    image: envoyproxy/envoy:v1.28.0
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ../certs:/etc/certs
